apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptime-kuma-backup
  namespace: uptime-kuma
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: uptime-kuma-backup
  namespace: uptime-kuma
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uptime-kuma-backup
  namespace: uptime-kuma
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: uptime-kuma-backup
subjects:
- kind: ServiceAccount
  name: uptime-kuma-backup
  namespace: uptime-kuma
