apiVersion: v1
kind: ConfigMap
metadata:
  name: version-sync-script
  namespace: {{ .Values.namespace }}
  labels:
    app: version-sync
data:
  update-uptime-kuma-version.py: |
{{ .Files.Get "scripts/update-uptime-kuma-version.py" | indent 4 }}