apiVersion: v2
name: uptime-kuma
description: Uptime Kuma monitoring application
version: 1.0.0
appVersion: "2.0.2"

dependencies:
  - name: uptime-kuma
    version: "2.22.0"
    repository: https://dirsigler.github.io/uptime-kuma-helm/