apiVersion: v2
name: uptime-kuma
description: Uptime Kuma monitoring application

dependencies:
  - name: uptime-kuma
    version: "2.22.0"
    repository: https://dirsigler.github.io/uptime-kuma-helm/