apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: kuma-versionizer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/hjukic/kuma-versionizer
      path: chart
      targetRevision: main
      helm:
        valueFiles:
          - $values/charts/kuma-versionizer/values.yaml
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma-versionizer
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true
  #     - ServerSideApply=true