apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: kuma-versionizer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Chart from external repository
    - repoURL: https://github.com/hjukic/kuma-versionizer
      path: chart
      targetRevision: main
      helm:
        valueFiles:
          - $values/charts/kuma-versionizer/values.yaml
    
    # Source 2: Values from your local repository
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      ref: values
      
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma-versionizer
    
  # Tell ArgoCD to merge values from source 2 into source 1
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
  #   automated:
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true
  #     - ServerSideApply=true