apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: uptime-kuma
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/uptime-kuma
    targetRevision: {{ .Values.global.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true
  #     - ServerSideApply=true